version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-changeme}
      POSTGRES_DB: ${DB_NAME:-myapp}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    environment:
      APP_NAME: ${APP_NAME:-Survey App}
      PORT: ${PORT:-8080}
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASS: ${DB_PASS:-changeme}
      DB_NAME: ${DB_NAME:-myapp}
      DB_SSLMODE: disable
    ports:
      - "${APP_PORT:-8080}:8080"
    depends_on:
      - db

volumes:
  pgdata:
